### ISSUE TITLE
I can't install it

### ISSUE THREAD

**Issue by KazukiKazuma** [abindent/nextwave#1]
I don't know if it's a me issue. But I can't install this via pip. It always says that : ERROR: Could not find a version that satisfies the requirement nextwave (from versions: 1.0.0a1, 1.0.0a2, 1.0.0a3, 1.0.0a4, 1.0.0, 1.0.1a0, 1.0.1a1)
ERROR: No matching distribution found for nextwave. Please can I get some help

**Comment by abindent** [comment]
Try `pip install nextwave==1.0.1a1`

**Comment by abindent** [comment]
is the problem solved???? @KazukiKazuma

**Comment by KazukiKazuma** [comment]
Hi, sorry for the late reply. Yes it worked all just fine now. Thank you very very much.
